// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file evm_indexer/v1/evm_indexer.proto (package evm_indexer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetLatestStoreLogsRequest, GetLatestStoreLogsResponse, GetStoreLogsRequest, GetStoreLogsResponse, GetStoreLogsStreamRequest, GetStoreLogsStreamResponse, GetStoresRequest, GetStoresResponse, StartPipelineRequest, StartPipelineResponse, StopPipelineRequest, StopPipelineResponse } from "./evm_indexer_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service evm_indexer.v1.EvmIndexerService
 */
export const EvmIndexerService = {
  typeName: "evm_indexer.v1.EvmIndexerService",
  methods: {
    /**
     * @generated from rpc evm_indexer.v1.EvmIndexerService.GetStores
     */
    getStores: {
      name: "GetStores",
      I: GetStoresRequest,
      O: GetStoresResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evm_indexer.v1.EvmIndexerService.StartPipeline
     */
    startPipeline: {
      name: "StartPipeline",
      I: StartPipelineRequest,
      O: StartPipelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evm_indexer.v1.EvmIndexerService.StopPipeline
     */
    stopPipeline: {
      name: "StopPipeline",
      I: StopPipelineRequest,
      O: StopPipelineResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evm_indexer.v1.EvmIndexerService.GetStoreLogs
     */
    getStoreLogs: {
      name: "GetStoreLogs",
      I: GetStoreLogsRequest,
      O: GetStoreLogsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evm_indexer.v1.EvmIndexerService.GetLatestsStoreLogs
     */
    getLatestsStoreLogs: {
      name: "GetLatestsStoreLogs",
      I: GetLatestStoreLogsRequest,
      O: GetLatestStoreLogsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc evm_indexer.v1.EvmIndexerService.GetStoreLogStream
     */
    getStoreLogStream: {
      name: "GetStoreLogStream",
      I: GetStoreLogsStreamRequest,
      O: GetStoreLogsStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

